### ISSUE TITLE
docker compose file not working on os x

### ISSUE THREAD

**Issue by zabojad** [eko/docker-symfony#2]
Hi there !

It's the first time I'm using docker so this might be a dumb issue: I've git pulled your repo, changed the occurences of ```FROM debian:jessie``` to ```FROM ubuntu:14.04``` and ran ```docker-compose up``` in the boot2docker terminal. I get this:
```bash
bash-3.2$ docker-compose up
Creating docker_application_1...
Pulling image symfony/code:latest...
Pulling repository symfony/code
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 31, in main
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 59, in perform_command
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 464, in up
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.project", line 208, in up
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.service", line 214, in recreate_containers
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.service", line 199, in create_container
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.progress_stream", line 37, in stream_output
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.progress_stream", line 50, in print_output_event
compose.progress_stream.StreamOutputError: Error: image symfony/code:latest not found
```

**Comment by B-Galati** [comment]
I think command `docker build -t symfony/code code` should solve your problem

**Comment by zabojad** [comment]
Yes, building the images solved the problem. But nothing seems to respond on http://symfony.dev/ nor http://symfony.dev:81/

**Comment by zabojad** [comment]
Few more info:

I've added this line to my /etc/hosts:
```
127.0.0.1	symfony.dev
```

My ```symfony``` folder is a symbolic link to ```..``` (containing my symfony structure).

**Comment by zabojad** [comment]
I've changed 127.0.0.1 to the VM address printed at boot2docker startup and it works...
