### ISSUE TITLE
Error: image symfony/code:latest not found

### ISSUE THREAD

**Issue by paq85** [eko/docker-symfony#8]
Hi,

I wanted to try this project out and I get following error

```bash
$ docker-compose up
Recreating dockersymfony_application_1...
Pulling application (symfony/code:latest)...
Pulling repository symfony/code
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 31, in main
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 34, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 66, in perform_command
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 460, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.project", line 230, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 332, in execute_convergence_plan
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 380, in recreate_container
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 208, in create_container
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 236, in ensure_image_exists
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 694, in pull
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.progress_stream", line 37, in stream_output
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.progress_stream", line 50, in print_output_event
compose.progress_stream.StreamOutputError: Error: image symfony/code:latest not found
```

**Comment by paq85** [comment]
I can see there's already answer for that question:
https://github.com/eko/docker-symfony/issues/4

Closing.
